### ISSUE TITLE
Adicionar um item "Como contribuir" no menu principal do site

### ISSUE THREAD

**Issue by aninhalacerda** [pyladies-brazil/br-pyladies-pelican#10]
Desta forma, como falei com a Gabriela, fica mais fácil do pessoal enviar as modificações para o site, como novo post, novo evento, nova líder da sua cidade. Além de juntar materiais como estes:
https://www.gitbook.com/book/brazilpyladies/handbook/details
http://brasil.pyladies.com/hangouts/2015/02/09/como-comecar-um-grupo-pyladies/

--reported by @taniaa 
moved from [issue #15](https://github.com/pyladies-brazil/br-pyladies/issues/15) on old repo

**Comment by katyanna** [comment]
[Done](https://github.com/pyladies-brazil/br-pyladies-pelican/commit/da1b79ecda5f4d29730acf7094907f4e65e054b9).
