### ISSUE TITLE
Adequar layout para que seja responsivo

### ISSUE THREAD

**Issue by rsip22** [pyladies-brazil/br-pyladies-pelican#100]
Está com scroll horizontal no iPad.

**Comment by jtemporal** [comment]
@rsip22 isso em todo o site ou  em alguma area especifica como descrito no #60 ? pode mandar uns prints aqui?!

**Comment by camilaavilarinho** [comment]
Resolvi esse problema do scroll aqui: #105 
Ele não estava considerando o tamanho da tela do iPad no media querie

**Comment by rsip22** [comment]
Continua com scroll. Na verdade, não tem barra embaixo, mas você precisa deslizar a tela para ver todo site. Em todas as partes do site.

**Comment by camilaavilarinho** [comment]
@rsip22 o PR ainda não foi aceito. 
Quando atualizar tu verifica de novo, aí se continuar com o scroll tu me avisa que eu tento arrumar novamente, mas quando fiz o teste no meu deu certo.

**Comment by rsip22** [comment]
Depois que escrevi que vi que o PR ainda estava lá. Sorry. 

Verifico sim. ^^

**Comment by rsip22** [comment]
Continua com scroll. :/

Print de como o site aparece no iPad.
![image](https://cloud.githubusercontent.com/assets/16676222/19582574/78997bb6-9714-11e6-8b76-8c29ee7b4e43.jpeg)

**Comment by rsip22** [comment]
A questão não é os 95%, é as colunas, que devem ser em número menor em viewport menor, acho.

Se ninguém conseguir desvendar isso, eu tento no final de semana.

**Comment by darlenedms** [comment]
Olá @rsip22, pode re-validar, por favor? 😄

**Comment by rsip22** [comment]
Agora funfeia!
