### ISSUE TITLE
Melhorar layout da página Eventos

### ISSUE THREAD

**Issue by camilaavilarinho** [pyladies-brazil/br-pyladies-pelican#104]
Quando o título do evento é muito grande, o espaço do evento fica maior que os outros, deixando o visual meio bagunçado. 
A sugestão de mudança é padronizar um tamanho para a caixa com a descrição dos eventos, para que todos fiquem do mesmo tamanho.

**Comment by camilaavilarinho** [comment]
Vou tentar resolver esse

**Comment by jtemporal** [comment]
@camilaavilarinho coloquei o label de help wanted pra se algm tiver alguma ideia poder discutir aqui ;)

**Comment by talitarossari** [comment]
Oi meninas, vcs precisam de ajuda?

**Comment by rsip22** [comment]
Não esqueça de botar o texto para quebrar, ou a caixa fica de tamanho fixo e o texto sai pra fora.

**Comment by talitarossari** [comment]
@rsip22, eu usei 50% no desktop, e 100% abaixo de 800px
Como eu disse no comentario do PR, é só uma coisa provisoria

**Comment by jtemporal** [comment]
aqui já fechou ne?

**Comment by talitarossari** [comment]
acredito que esta OK, pelo menos o que foi pedido

**Comment by rsip22** [comment]
Ficou bem melhor. ^^

OBS: Creio que só o pessoal da organização tem permissão pra fechar issue, porque não consegui... u.u
