### ISSUE TITLE
Colocar link para a lista de e-mails

### ISSUE THREAD

**Issue by rsip22** [pyladies-brazil/br-pyladies-pelican#109]
Acho que seria interessante ter o link pra lista de e-mails em um lugar acessível no site (por exemplo, próximo do link das redes sociais).

**Comment by Monamello** [comment]
lista de emails das ladies?

**Comment by jtemporal** [comment]
pyladiesbrazil@googlegroups.com essa lista né?! @pgrangeiro ou @darlenedms qual o link q leva pro pedido de participação da lista, n lembro =/

**Comment by rsip22** [comment]
Esse link tá ótimo já.

**Comment by kessiacastro** [comment]
Vou fazer! :D Penso em colocar um icon igual o do site da python brasil e coloco umas tooltips nos icons só por via das dúvidas?

**Comment by rsip22** [comment]
Como achar melhor

**Comment by pgrangeiro** [comment]
@jtemporal o link pra se inscrever no grupo é este aqui https://groups.google.com/forum/#!forum/pyladiesbrazil

**Comment by pgrangeiro** [comment]
Corrigido no PR #119
