### ISSUE TITLE
Trocar a foto de fundo do invite-app do Slack

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/br-pyladies-pelican#110]
Por equanto o [app de convite](http://brasil-pyladies.herokuapp.com/) do Slack ta com a foto default. 
seria mais legal se colocassemos uma tipo essa aqui
https://www.flickr.com/photos/pythonbrasil/30418358526/in/album-72157671939963093/

**Comment by jtemporal** [comment]
Repo pra alterar a imagem...
https://github.com/pyladies-brazil/slack-invite

**Comment by annanda** [comment]
Fazendo.

**Comment by annanda** [comment]
Done!
