### ISSUE TITLE
Menu mobile não funciona

### ISSUE THREAD

**Issue by darlenedms** [pyladies-brazil/br-pyladies-pelican#111]

**Comment by rsip22** [comment]
Por favor, dê mais detalhes. Não dá pra clicar, ele está bagunçado, não aparecem as palavras...? Qual sistema operacional e telefone?

**Comment by lusac** [comment]
Da uma olhada nesse PR #115 :)

**Comment by pgrangeiro** [comment]
Obrigada @lusac 
Resolvido no PR #115

**Comment by rsip22** [comment]
Não funfeia no iPad. 

Vejam no print, os menus "Sobre" e "Eventos" ficam sobrepostos pelo logo... algo me diz que isso não deveria acontecer. 

![img_1675](https://cloud.githubusercontent.com/assets/16676222/19903111/88516eda-a054-11e6-82ad-9007a62e6e7e.PNG)

**Comment by jtemporal** [comment]
@rsip22 a issue #141 foi criada pra resolver isso =)
