### ISSUE TITLE
Conectando sites Python.org.br e brasil.pyladies.com

### ISSUE THREAD

**Issue by filipecifali** [pyladies-brazil/br-pyladies-pelican#112]
Seria possível gerar um widget ou uma página simplificada do /locations para anexarmos no Pelican do site python.org.br? 

Imagino que assim seria a maneira mais fácil de que não precisemos atualizar dois sites.

Se vocês preferirem, podemos adicionar somente um link para o location, estamos abertos a comentários na issue lá também qualquer coisa :+1: 

Issue referente no repositório https://github.com/pythonbrasil/wiki/issues/66

**Comment by pgrangeiro** [comment]
Oi @filipecifali . O site do pyladies já contém [um arquivo](https://github.com/pyladies-brazil/br-pyladies-pelican/blob/master/data/locations.yml) que possui os dados de todas as comunidades pyladies pelo Brasil. Como somos nós quem mantemos as informações, o mais correto seria quem quiser se manter atualizado implementar algum serviço que consuma os nossos dados.
