### ISSUE TITLE
PyLadies Brasil logo na home

### ISSUE THREAD

**Issue by aninhalacerda** [pyladies-brazil/br-pyladies-pelican#12]
não tem nada na página inicial que indique que estamos no PyLadies Brasil. Seria legal ter um logo maior e que identificasse o país.

**Comment by aninhalacerda** [comment]
Acho que agora que já está identificando o país podemos fechar essa issue.

Que acham?

<img width="172" alt="screen shot 2015-12-03 at 11 55 17 am" src="https://cloud.githubusercontent.com/assets/626988/11563829/c6f43c82-99b4-11e5-807a-c9b1bb4367f5.png">

**Comment by ellisonleao** [comment]
:+1:
