### ISSUE TITLE
Adicionar dados do PyLadies PUC-Rio

### ISSUE THREAD

**Issue by pgrangeiro** [pyladies-brazil/br-pyladies-pelican#129]
Adicionar PyLadies PUC-Rio na listagem de locais

**Comment by darlenedms** [comment]
@tfalbo pode nos ajudar com isso?

**Comment by tfalbo** [comment]
Posso sim!! Envio o PR até o fds. :)

**Comment by tfalbo** [comment]
Mandei o PR #145

**Comment by jtemporal** [comment]
closed by #145
