### ISSUE TITLE
Mover a documentação para um local mais intuitivo

### ISSUE THREAD

**Issue by gabisurita** [pyladies-brazil/br-pyladies-pelican#137]
Eu sugiro tirar a documentação de CONTRIBUTING, pois é um lugar pouco intuitivo para procurar informação de instalação e configuração. Acho que ela ficaria melhor no próprio README, um ReadTheDocs ou até em uma wiki do Github.

O que acham?

**Comment by taniaa** [comment]
Olá, na verdade no README já tem um link para CONTRIBUTING, então acredito que esteja ok, veja:

"""
Contribuindo

Para contribuir com o projeto veja o guia de Contribuição.
"""

Fonte: https://github.com/pyladies-brazil/br-pyladies-pelican/blob/master/README.md

**Comment by gabisurita** [comment]
Eu vi. Eu só não acho que o contrib é o lugar mais adequado para colocar informação de instalação e configuração. Eu acho que pelo menos a seção `Preparando o ambiente local` deveria ficar no `README` e não no `CONTRIBUTING`, já que tem uma boa parte já redundante.

Também acho que as outras informações talvez ficassem mais estruturadas e acessíveis na Wiki ou num RTD, mas enfim, tudo isso é chatisse minha hs... se não acharem pertinente acho que não tem problema :)
