### ISSUE TITLE
Criar conteudo de revisão de PRs

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/br-pyladies-pelican#140]
Não está claro como os PRs feitos são avaliados e testados... A ideia seria criar um parte no CONTRIBUTING.md que falasse disso, até pra ajudar quem queira revisar PRs e não saiba como fazê-los.

**Comment by Raffesmind** [comment]
@jtemporal posso preparar uma primeira versão de texto sobre boas práticas, dicas e observações quando estiver analisando?

**Comment by jtemporal** [comment]
manda ai @Raffesmind

**Comment by jtemporal** [comment]
-> todo PR chega para develop. isso abre um [deploy para o staging](http://staging-brasil-pyladies.herokuapp.com)
-> o status de todos os deploys podem ser vistos no [codeship](https://app.codeship.com/projects/203211)
-> confere-se se o build de staging foi bem sucedido pelo codeship
-> confere-se o staging pra ver se ta tudo no lugar como deveria
-> caso positivo é só abrir e liberar um PR para a master como o #175 esse PR sendo merged libera a ação de deploy em produção. (também pode ser acompanhada pelo codeship)

**Comment by biancarosa** [comment]
Acho que já atacamos isso!
