### ISSUE TITLE
Menu com problemas em tamanhos médios

### ISSUE THREAD

**Issue by gabisurita** [pyladies-brazil/br-pyladies-pelican#141]
O menu está com problemas e comportamento inconsistente em tamanhos médios:

**660px:**
![640px](https://cloud.githubusercontent.com/assets/4023375/19910690/dbf04e00-a075-11e6-8703-db99f603bf5f.png)

**720px** (nota que neste tamanho uma parte do menu não aparece)
![720px](https://cloud.githubusercontent.com/assets/4023375/19910779/465052ea-a076-11e6-8aae-11f17ea5a595.png)

**800px:**
![800px](https://cloud.githubusercontent.com/assets/4023375/19910753/2477ce78-a076-11e6-8b2c-4128e936c99d.png)

**Comment by lusac** [comment]
@gabisurita Veja se resolve #150 :)

**Comment by darlenedms** [comment]
Resolvido em https://github.com/pyladies-brazil/br-pyladies-pelican/pull/150 😸
