### ISSUE TITLE
Contribuir usando Windows

### ISSUE THREAD

**Issue by rsip22** [pyladies-brazil/br-pyladies-pelican#162]
Tem alguma forma de contribuir usando Windows? (sim, eu estou perguntando isso) Houve muitos problemas tentando resolver isso e dar o comando Make no Windows durante a sprint na PythonSul - não consegui resolver.

Alguém pode montar uma documentação indicando passo a passo?

**Comment by alini-x** [comment]
Não entendi o que você quis dizer com contribuir, seria com a issues? Poderia me explicar melhor o que tá rolando quando vai dar o usar o Make file?

**Comment by jtemporal** [comment]
acho que o problema @alini-x é que Makefile não funciona no windows...

**Comment by elyssonmr** [comment]
Existe um exemplo em uma outra lib Python. Dai facilitaria o desenvolvimento pelo Windows.

**Comment by gabisurita** [comment]
Minha sugestão é usar o cygwin, que emula um ambiente unix-like dentro do Windows.

Tutorial: https://www.elastichosts.com/blog/installing-cygwin-on-windows-for-linux-tools/
Ref: http://www.cygwin.com/

**Comment by danipj** [comment]
Eu desenvolvo no windows com Git Bash e o make eu instalei graças a esse gist:
https://gist.github.com/evanwill/0207876c3243bbb6863e65ec5dc3f058

**Comment by dandaramcsousa** [comment]
Posso fazer um update no readme com um tutorial para rodar no Windows? Já tô expert em fazer essas coisas e tenho um tutorial de instalação de Docker no windows tb.
@biancarosa @cecivieira @giovana-morais e a quem mais puxar este bonde

**Comment by giovana-morais** [comment]
@dandaramcsousa  manda bala
