### ISSUE TITLE
Link da lojinha não funciona

### ISSUE THREAD

**Issue by rsip22** [pyladies-brazil/br-pyladies-pelican#165]
Link que tem na barra de navegação do site retorna erro 404.

**Comment by Dayof** [comment]
A lojinha está fora do ar pois está sendo reescrita. A sugestão temporária é que seja removido o link da Lojinha no site das PyLadies Brasil como é mostrado na imagem abaixo. O que acha?

![captura de tela 2017-10-09 as 00 52 24](https://user-images.githubusercontent.com/8198348/31324797-cf5e9150-ac8c-11e7-9f78-402126261d59.png)

**Comment by darlenedms** [comment]
Link removido no commit 54453a6b4381f78c2f11f849a65fd40d3b1becee. Podemos fechar essa issue?

**Comment by jtemporal** [comment]
Fechando ;)

**Comment by jtemporal** [comment]
Quando a lojinha estiver no ar de novo abrimos nova issue pra recolocação do link :)
