### ISSUE TITLE
Ajustes visuais

### ISSUE THREAD

**Issue by humrochagf** [pyladies-brazil/br-pyladies-pelican#18]
Olá, fiz o fork do projeto e notei alguns probleminhas no layout.
Aproveitei que estava com tempo livre e já realizei as correções no PR #17 

Abaixo está a lista dos ajustes:
- Grid de localizações desalinhado
- Menu na versão mobile atrás do conteúdo
- Grid quebrado no mobile

**Comment by ellisonleao** [comment]
Arrumado em #17 . Valeu @humrochagf !
