### ISSUE TITLE
Esclarecer os passos de Instalação do Repo

### ISSUE THREAD

**Issue by amandachagas** [pyladies-brazil/br-pyladies-pelican#199]
Bom dia meninas, 

Eu já tive problemas com isso e ouvi relatos dessa mesma situação... Ao seguir os passos do readme de instalação do repositório com a vm ativada da problema no make.

Então, eu acho que uma nota no próprio readme clarificando que esse comando já irá criar uma vm, logo a pessoa deve rodá-lo fora da vm, traria benefícios para quem clonar/executar o repo.

Valeu!

**Comment by amandachagas** [comment]
Deixei dessa forma(#200):

**Comment by jtemporal** [comment]
fechando pq já foi resolvida no #200
