### ISSUE TITLE
url -> heroku staging

### ISSUE THREAD

**Issue by katyanna** [pyladies-brazil/br-pyladies-pelican#20]
Qualquer mudança de página no site muda a url de brasil-pyladies.com/# para staging-brasil-pyladies.herokuapp.com/#

**Comment by aninhalacerda** [comment]
Oi @katyanna .

Nossa configuração de escolha de qual URL deve ser usada não está funcionando corretamente. Escolhemos qual URL usar para criar o site no arquivo [publishconf.py](https://github.com/pyladies-brazil/br-pyladies-pelican/blob/master/publishconf.py)

<img width="520" alt="screen shot 2015-12-03 at 10 40 54 am" src="https://cloud.githubusercontent.com/assets/626988/11562097/80d300da-99aa-11e5-8797-d1d8b1b32071.png">

É preciso investigar porque a verificação da variável ENV não está funcionando. Ou se ela está sendo enviada corretamente no nosso setup no [SnapCI](https://snap-ci.com/pyladies-brazil/br-pyladies-pelican/branch/master) (step production).

<img width="580" alt="screen shot 2015-12-03 at 10 52 52 am" src="https://cloud.githubusercontent.com/assets/626988/11562307/0853e456-99ac-11e5-99ac-6e677e8c9d39.png">

Também é possível investigar como passar variáveis de ambiente usando o [Buildpack](https://github.com/pyladies-brazil/heroku-buildpack-pelican) que utilizamos para rodar o pelican no heroku. - no arquivo [/bin/compile](https://github.com/pyladies-brazil/heroku-buildpack-pelican/blob/master/bin/compile)

**Comment by rsip22** [comment]
Tentei ajudar, gente, mas só no meu gh-pages que ficou com os links corretos. Não sei como, então, sorry. :( Acho que só quem tem acesso ao Heroku mesmo.

**Comment by ellisonleao** [comment]
@katyanna https://github.com/pyladies-brazil/br-pyladies-pelican/commit/18cdc039bacf0e17cafa3b6ee46faa242844e8aa resolveu essa issue. Acho que podemos fechar.

**Comment by darlenedms** [comment]
@ellisonleao Na verdade essa issue ainda não foi resolvida, a única coisa que fiz foi "passar o problema" pra staging ao invés de prod (coloquei a url de produção como a padrão).

A variável de ambiente `ENV` que definimos no SnapCI e/ou nas config vars do Heroku não fica disponível em tempo de compilação, que é justamente quando precisamos.
Pra funcionar como queremos, devemos usar `ENV_DIR` no buildpack (https://devcenter.heroku.com/articles/buildpack-api#bin-compile) mas ainda não consegui fazer isso. 😢

**Comment by darlenedms** [comment]
@ellisonleao @katyanna @rsip22 @aninhalacerda Acho que consegui 😄 
Já fiz o merge das alterações no buildpack, por favor validem os links em prod e staging.

**Comment by ellisonleao** [comment]
👍

**Comment by aninhalacerda** [comment]
👍 Muito bom @darlenedms . Obrigada por ter pego essa issue!
