### ISSUE TITLE
Indexar vídeos das palestras desse ano

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/br-pyladies-pelican#206]
Esse ano rolaram alguns eventos e varios desses possuem palestras por pyladies.
Se mandarem os links aqui eu garanto que coloco elas no site.

**Comment by anapauladsmendes** [comment]
Anexei os vídeos de 2016 e de 2017. Fechando a issue. :)

**Comment by anapaulamendes** [comment]
Anexei os vídeos de 2016 e de 2017. Fechando a issue. :)
