### ISSUE TITLE
Atualização do CONTRIBUTING.md

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/br-pyladies-pelican#208]
Hoje o site roda normalmente na versão mais atual do Python: `3.6.4`.
Acho que da pra atualizar o arquivo de contribuição.

**Comment by letuche** [comment]
É só trocar `2.7` por `3.6.4` no texto?

**Comment by jtemporal** [comment]
acredito que sim @letuche

**Comment by anapaulamendes** [comment]
Estou fechando a issue, visto que ela já foi resolvida. :)
