### ISSUE TITLE
/archives está 404

### ISSUE THREAD

**Issue by katyanna** [pyladies-brazil/br-pyladies-pelican#21]
![screen shot 2015-11-27 at 10 16 59 pm](https://cloud.githubusercontent.com/assets/1137200/11449452/9c80e9a0-9554-11e5-94ae-0d15fef247e6.png)

**Comment by aninhalacerda** [comment]
Me parece que a página /archives, que no antigo site mostrava uma lista com todos os blog posts, não foi migrada para o Pelican. 

Deveria existir uma página 'archives' em https://github.com/pyladies-brazil/br-pyladies-pelican/tree/master/content/pages

Vou retirar o link do menu para fechar esse bug e criar uma nova issue de feature para criar essa page.

**Comment by ellisonleao** [comment]
Realmente não foi migrada @aninhalacerda . Perdão pelo vacilo hehe :smile:

**Comment by aninhalacerda** [comment]
Sem problemas @ellisonleao . Acabei de criar a issue #23 para criarmos essa página.
