### ISSUE TITLE
Ajustar layout na fotos do post  "Um ENORME obrigada!" na sessão de Blog

### ISSUE THREAD

**Issue by aranhaqg** [pyladies-brazil/br-pyladies-pelican#217]
Erro está ocorrendo apenas no ambiente de stagging (branch develop): 
https://staging-brasil-pyladies.herokuapp.com/2018/03/14/agradecimentos-campanha-pybr-13/

Na listagem de "beneficiadas" do post aparece uma linha próxima a fotos de cada uma. Esta linha deve ser ajustada. 
<img width="604" alt="erro-pyladies" src="https://user-images.githubusercontent.com/1275896/39015631-57b2bfdc-43f4-11e8-8cdb-eea1d65396fb.png">

**Comment by humrochagf** [comment]
Fiz o ajuste removendo a barra e aproveitei para ajustar o layout na versão mobile que das fotos que estavam um pouco apertadas :blush:

**Comment by anapaulamendes** [comment]
Obrigada, @humrochagf ! Fechando a issue. :)
