### ISSUE TITLE
Quebra de Layout

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/br-pyladies-pelican#229]
Na parte de locais do site do Pyladies, o grupo `São José dos Campos - SP` tem um nome muito grande quebrando o layout:

![screenshot from 2018-10-27 12 41 15](https://user-images.githubusercontent.com/6595551/47606094-ce7f7d80-d9e5-11e8-9f19-f4e5ebbd58e6.png)

Uma possibilidade de solução, é reduzir o tamanho da fonte  para `15px` (hoje o tamanho é `16px`) :

![screenshot from 2018-10-27 12 41 54](https://user-images.githubusercontent.com/6595551/47606099-dd663000-d9e5-11e8-9e1b-034d518fe340.png)

**Comment by NayraKaline** [comment]
vou tentar arrumar :)

**Comment by jtemporal** [comment]
precisar de ajuda @NayraKaline avisa ;)

**Comment by NayraKaline** [comment]
viu, tá certinho em todos os viewports que testei :c 
vou commitar algumas mudanças só pra garantir então!
