### ISSUE TITLE
Criar página para mostrar uma lista de posts

### ISSUE THREAD

**Issue by aninhalacerda** [pyladies-brazil/br-pyladies-pelican#23]
Inserir link "Blog" no menu principal que mostra uma página apenas com uma lista de títulos e autoras de cada blog post

obs. O template /archives (que era utilizado antes) já existe em themes/default/templates/archives.html
##### Tasks:
- Adicionar o link no menu em pelicanconf.py
  `MENUITEMS = (  
   ('Sobre', '/about'),  
   ('Eventos', '/events'),  
   ('Locais', '/locations'),  
   ('Ladies', '/ladies'),  
   ('Videos', '/videos'),  
  )`
- Criar page em content/pages com o template archives

**Comment by ellisonleao** [comment]
@aninhalacerda o link /archives está funcionando aqui http://pyladies-brazil.github.io/br-pyladies-pelican/archives

Criei o link aqui https://github.com/pyladies-brazil/br-pyladies-pelican/commit/6da14985cb029981bb0e65ae4691e8f76d91fe8a

**Comment by aninhalacerda** [comment]
@ellisonleao não sei porque não está funcionando em staging (https://staging-brasil-pyladies.herokuapp.com/archives) é preciso investigar.

**Comment by darlenedms** [comment]
@aninhalacerda e @ellisonleao podem revalidar em produção, por favor? http://brasil.pyladies.com/archives.html

**Comment by ellisonleao** [comment]
Agora está ok! 👍
