### ISSUE TITLE
Título do post não está aparecendo

### ISSUE THREAD

**Issue by aninhalacerda** [pyladies-brazil/br-pyladies-pelican#24]
Quando abrimos um post o título não aparece na página.

<img width="1160" alt="screen shot 2015-12-03 at 11 44 24 am" src="https://cloud.githubusercontent.com/assets/626988/11563559/5621e01e-99b3-11e5-8d05-2622732e3b28.png">

Issue: o título deveria aparecer neste espaço em branco

**Comment by ellisonleao** [comment]
Resolvido em https://github.com/pyladies-brazil/br-pyladies-pelican/commit/3ae3eed0ac667a680a8a377c5fb2e5be10c6351b
