### ISSUE TITLE
Problemas layout mobile na página de posts

### ISSUE THREAD

**Issue by ellisonleao** [pyladies-brazil/br-pyladies-pelican#27]
Alguns problemas ainda continuam
- Botão do menu mobile não aparece em posts. Um fix para as outras páginas foi feito em #26 

![screen shot 2015-12-03 at 4 05 19 pm](https://cloud.githubusercontent.com/assets/178641/11569223/de0a410a-99d7-11e5-98d3-bdb1eb19a4be.png)
- Título post não aparece em ambos os templates (mobile, desktop) #24

**Comment by darlenedms** [comment]
@ellisonleao pode revalidar essa issue, por favor? Exemplo: http://brasil.pyladies.com/2016/07/26/pyladies-no-fisl17/

**Comment by ellisonleao** [comment]
Agora está ok! Obrigado @darlenedms !
