### ISSUE TITLE
Organizar as pyladies por estado e região

### ISSUE THREAD

**Issue by ghost** [pyladies-brazil/br-pyladies-pelican#284]
Seria legal que as pyladies fossem organizadas por estado e região, isso tornaria o processo de busca mais simples.

**Comment by ghost** [comment]
Foi feito esse PR: #283. Porém, ainda seria melhor se a ordenação fosse automática.

**Comment by biancarosa** [comment]
Talvez um arquivo pra cada chapter faça mais sentido, não?

**Comment by biancarosa** [comment]
Ah, de locations acho que é bom que fique no mesmo arquivo. Mas cada chapter talvez pudesse ter seu proprio yaml de ladies.

**Comment by cecivieira** [comment]
Sessão Ladies excluída, conforme discussão da issue #356
