### ISSUE TITLE
Site Pyladies RJ não encontrado

### ISSUE THREAD

**Issue by ggarnier** [pyladies-brazil/br-pyladies-pelican#285]
O site http://rio.pyladies.com está dando "não encontrado". Há um link para esse endereço aqui: https://github.com/pyladies-brazil/br-pyladies-pelican/blob/987f4ff86a4409e4b7cb8a17d748e4c7e1b7f2b8/data/locations.yml#L119

O Facebook do grupo também tem um link para lá: https://www.facebook.com/pyladiesrio

**Comment by biancarosa** [comment]
Oi @ggarnier. Estamos em contato com o Pyladies Internacional pra recuperar o subdominio, deu algum problema nos ultimos meses.

**Comment by biancarosa** [comment]
Voltou a funcionar ;)
