### ISSUE TITLE
Atualizar a template/logo do site para a cor/logo nova

### ISSUE THREAD

**Issue by anapaulamendes** [pyladies-brazil/br-pyladies-pelican#291]
Para deixar o site mais caraterístico, atualizar para a template com a cor azul da logo nova e migrar as logos antigas para a nova.

**Comment by jtemporal** [comment]
As imagens oficiais e com alta qualidade da marca [podem ser encontradas aqui](https://drive.google.com/drive/folders/1ZL4NC8U2Z9krradjY90bDFawomRTZ5kR?usp=sharing)

Se alguém estiver problemas de acesso me da um alo

**Comment by anapaulamendes** [comment]
@jtemporal abriu de boas :smile:

**Comment by biancarosa** [comment]
só vamos, to tocando aqui

**Comment by biancarosa** [comment]
:rocket:
