### ISSUE TITLE
[Discussão] [Bug] Página Eventos 

### ISSUE THREAD

**Issue by anapaulamendes** [pyladies-brazil/br-pyladies-pelican#293]
Algumas caixinhas não estão alinhadas e ficam buracos de espaço.

**Comment by jtemporal** [comment]
@anapaulamendes pode dar mais detalhes? tipo print, navegador que testou e afins?

**Comment by luabras** [comment]
Acabei de testar no chrome, segue prints:
![2019-11-20 21_57_42-Pyladies Brasil](https://user-images.githubusercontent.com/14370234/69291093-e02f5680-0be0-11ea-901a-e4b1bc0c4e35.png)

![2019-11-20 21_57_08-Pyladies Brasil](https://user-images.githubusercontent.com/14370234/69291091-e02f5680-0be0-11ea-9559-65b6c686c533.png)
![2019-11-20 21_57_32-Pyladies Brasil](https://user-images.githubusercontent.com/14370234/69291092-e02f5680-0be0-11ea-9cd7-fd9abe4d77ed.png)

**Comment by anapaulamendes** [comment]
Muito obrigada, @luabras :heart:

**Comment by jtemporal** [comment]
Acho que a quebra vem por causa dos tamanho variáveis dos cards... alguém manja de deixar tudo com a mesma altura?

**Comment by biancarosa** [comment]
Acho que aqui é os dois: um bug e uma discussão. Queremos manter esse layout? Gostariamos de melhorar como pegamos esses eventos?

**Comment by giovana-morais** [comment]
eu acho que pra essa página esse layout de coluna fica mais bonitinho e a informação fica mais concentrada, uma vez que são mais eventos. mas isso é opinião pessoal. hahaha

**Comment by cecivieira** [comment]
Acho que essa página seria relevante, caso as informações estivessem atualizadas. No entanto, não estamos tendo muito sucesso com isso, então acho que poderia ser retirada.
