### ISSUE TITLE
Corrigir fotos quebradas em ladies

### ISSUE THREAD

**Issue by anapaulamendes** [pyladies-brazil/br-pyladies-pelican#296]

**Comment by jtemporal** [comment]
@anapaulamendes coloca mais detalhes aqui? print das quebras ou os nomes das pyladies com as fotos quebradas? assim a gnt faz um checklist ou um conjunto de issues com isso e também fica mais facil de organizar informações tipo novas fotos

**Comment by luabras** [comment]
As fotos quebradas são de Juciane Barros, Letícia Silva e Natália Catunda. Verifiquei aqui e as duas primeiras no ladies.yml estão apontando as fotos para arquivos na pasta images, porém os arquivos não estão lá. A última aponta para um link de imagem que acaba direcionando para um canal do youtube.
![2019-11-20 21_47_02-Pyladies Brasil](https://user-images.githubusercontent.com/14370234/69290844-fee11d80-0bdf-11ea-8d92-26f0693e1acb.png)
![2019-11-20 21_47_12-Pyladies Brasil](https://user-images.githubusercontent.com/14370234/69290845-fee11d80-0bdf-11ea-8381-e7ebf1eedc5f.png)
![2019-11-20 21_47_19-Pyladies Brasil](https://user-images.githubusercontent.com/14370234/69290849-fee11d80-0bdf-11ea-9f20-d504f798dcd4.png)

**Comment by anapaulamendes** [comment]
Muito obrigada, @luabras :heart:

**Comment by anapaulamendes** [comment]
Uma sugestão é que tiremos do manual de contribuição a opção de poder adicionar link para a foto, porque quando o link quebrar por qualquer motivo, a foto vai quebrar no site, é melhor subir a foto na pastinha das ladies.

**Comment by jtemporal** [comment]
@nataliacatundafr @leticiadasilva @JucianeBarros vocês podem ou mandar aqui um link pra uma foto de vocês ou mandar um pull request atualizando por gentileza?

**Comment by ghost** [comment]
Certo! @jtemporal 
Aqui o link: https://images.app.goo.gl/kEDm8DMnKkXbWnUm7

**Comment by giovana-morais** [comment]
@nataliacatundafr a página de ladies foi excluída como discutido em #356 , portanto não haverá atualização referente à imagem e essa issue permanece encerrada. :wink:
