### ISSUE TITLE
Permitir urls absolutas no field image do arquivo ladies.yml 

### ISSUE THREAD

**Issue by ellisonleao** [pyladies-brazil/br-pyladies-pelican#30]
Problema:
https://github.com/pyladies-brazil/br-pyladies-pelican/commit/83e3d2396cce011d056bc4aa5507ac5ae8dc248c

Isso hoje está gerando uma url do tipo

`https://staging-brasil-pyladies.herokuapp.comhttps://pbs.twimg.com/profile_images/689436826294099968/43rAUWn3.jpg`

**Comment by darlenedms** [comment]
@ellisonleao Pode validar, por favor :]

**Comment by ellisonleao** [comment]
@darlenedms  por mim tá tranquilo, só precisa dar uma reforçada que o path vai ser relativo na [seção de contributing para ladies](https://github.com/pyladies-brazil/br-pyladies-pelican/blob/master/CONTRIBUTING.md#adicionar-ladies) . Pode ser que mais pra frente da pra pensar em fazer um macro que cheque os 2 casos. Valeu pelo fix! 😄

**Comment by darlenedms** [comment]
@ellisonleao Atualizei o [CONTRIBUTING.md](https://github.com/pyladies-brazil/br-pyladies-pelican/blob/master/CONTRIBUTING.md#adicionar-ladies), o que acha?

**Comment by ellisonleao** [comment]
Legal! Vou fechar! Obrigado @darlenedms !
