### ISSUE TITLE
Adicionar CI no pull-request

### ISSUE THREAD

**Issue by biancarosa** [pyladies-brazil/br-pyladies-pelican#336]

**Comment by jtemporal** [comment]
opções: 
 - Actions do github
 - Travis

**Comment by biancarosa** [comment]
vou tentar ver se rola com github actions!

**Comment by biancarosa** [comment]
fiz uma tentativa aqui #351 mas parece que ja ativamos o build via codeship pros PRs, não sei se vale a pena insistir muito nela :thinking:

**Comment by biancarosa** [comment]
fechando por enquanto, o CI do codeship ta bonitinho ali, depois vemos se vamos mudar de plataforma
