### ISSUE TITLE
Revisar Makefile

### ISSUE THREAD

**Issue by biancarosa** [pyladies-brazil/br-pyladies-pelican#338]
Sugestão: revisar Makefile, tem muita coisa não usada, pode ser só o básico pra conseguir rodar o projeto, o proprio codeship não usa ele

**Comment by giovana-morais** [comment]
será que é interessante colocar na mesma tarefa validar a compatibilidade com outros sistemas operacionais ou deixamos isso em uma tarefa separada?

**Comment by BrunaNayara** [comment]
Vi que vc marcou essa tarefa como `doing` @giovana-morais.
Esse fim de semana posso rodar o projeto e ver o que podemos melhorar no Makefile e te dou um toque lá no slack, pode ser? :)

**Comment by giovana-morais** [comment]
claro! o Makefile que temos por enquanto é gerado pelo próprio pelican. comecei a reduzir algumas coisas, mas ainda nada significativo. faltou um pouco de tempo hehehe
qualquer coisa dá um toque por lá
