### ISSUE TITLE
[Discussão] Deletar o arquivo de ladies

### ISSUE THREAD

**Issue by giovana-morais** [pyladies-brazil/br-pyladies-pelican#356]
A [página de Ladies](http://brasil.pyladies.com/ladies/) é uma página que gera alguns problemas  devido à desatualização, links quebrados, imagens faltantes e etc. Se olharmos os nossos [PRs sem atividade](https://github.com/pyladies-brazil/br-pyladies-pelican/pulls?q=is%3Apr+label%3Awontfix+) a grande maioria é referente a essa página também.

Além disso, é sempre muito difícil manter ela atualizada porque novas participantes chegam a todo momento, assim como participantes saem.

Em uma discussão com @pyladies-brazil/tech-team levantamos a possibilidade de excluir essa página e gostaríamos de conversar sobre prós e contras com a comunidade antes de tomarmos essa decisão.

Deixa tua opinião e votar aqui até dia 29 maio: 👍(sim, pode excluir essa página) 👎(não, acho melhor mantê-la).

**Comment by cecivieira** [comment]
+1

Acho que o site deveria ser um instrumento com informações atualizadas das comunidades e a página Ladies não faz muito sentido nesse contexto, além de sempre estar desatualizada.

**Comment by mrncstt** [comment]
👍

**Comment by desi-me** [comment]
👍

**Comment by tiidadavena** [comment]
👍🏻
Acho válido manter sim, mas como uma landing page, te direcionando para as redes sociais e links de acesso para os outros chapters. Porém, como blog, não acho que funciona (se não tiver ngm exclusivo pra isso).
