### ISSUE TITLE
[Discussão] Utilizar a branch master como principal 

### ISSUE THREAD

**Issue by biancarosa** [pyladies-brazil/br-pyladies-pelican#357]
Com o deploy preview que adicionamos recentemente, cada pull-request pode ser validado num ambiente de teste no Netlify e o ambiente de staging perde seu uso.

Pra isso precisaríamos:

- [x] Alterar configuração do github
- [x] Alterar as docs de contribuição
- [x] Proteger o ambiente de master para que as mudanças apenas cheguem nele através de pull-request (seguindo Feature Branch Development, mesmo para quem tem acesso admin - https://martinfowler.com/bliki/FeatureBranch.html)

**Comment by giovana-morais** [comment]
eu acho a ideia ótima. nesse caso a gente mataria o codeship também ou deixaria ele?

**Comment by jtemporal** [comment]
Acho uma ótima ideia! Acho que vai facilitar o processo de contribuição agora que temos o preview.

Pergunta: Com o preview do Netlify podemos matar também a app de staging do Heroku correto?

**Comment by biancarosa** [comment]
Podemos matar a app de staging sim, @jtemporal!

@giovana-morais, podemos matar o codeship caso a gente traga pro github actions / travis ci o deploy no heroku ou use o netilify ponta a ponta, mas pra substituir o heroku em prod acho que vai ser uma tarefa um pouco mais demorada pq depende de mudanças do subdominio

**Comment by jtemporal** [comment]
> mas pra substituir o heroku em prod acho que vai ser uma tarefa um pouco mais demorada pq depende de mudanças do subdominio

para isso a gente precisa da ajuda do pessoal internacional que gerencia os dominios e subdominios para ajustarem os apontamentos para o lugar certo

**Comment by jtemporal** [comment]
> Podemos matar a app de staging sim, @jtemporal!

@biancarosa vou fazer isso no próximo final de semana então, qualquer mudança de planos [me avisem no telegram](https://t.me/jtemporal) por gentileza!

**Comment by biancarosa** [comment]
Fechado pq já estamos usando master! Levei a discusão do netlify como ambiente principal pra issue #364
