### ISSUE TITLE
[BUG] Corrigir layout da página inicial

### ISSUE THREAD

**Issue by biancarosa** [pyladies-brazil/br-pyladies-pelican#361]
**Descreva o bug**
Layout da pagina inicial está completamente quebrado

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá até http://brazil.pyladies.com/
2. Observe o caos

**Comportamento esperado**
Queria que não estivesse quebrado

**Screenshots**
![Screenshot from 2020-05-17 13-21-03](https://user-images.githubusercontent.com/1480558/82153998-58e63700-9841-11ea-9792-c30bc4f4da8e.png)

**Desktop (complete com as seguintes informações, se aplicável):**
 Todos os que vi até agora. Se pegar um caso diferente por favor comentar na issue.

**Contexto adicional**
Acho que pode ter a ver com o tamanho do titulo, mas acho que nenhum titulo deveria quebrar!

**Comment by jtemporal** [comment]
Uma informação adicional: O preview do texto de cada post é um pedacinho do começo do texto, textos que contém imagem no início do texto (além do tamanho do título) também quebram a formatação...
