### ISSUE TITLE
[Discussão] Licença para o código

### ISSUE THREAD

**Issue by cecivieira** [pyladies-brazil/br-pyladies-pelican#377]
Percebi que o código do site não tem licença, ou seja, teoricamente ninguém tá autorizado a reutilizá-lo.

Minha sugestão é usar a [licença MIT](https://opensource.org/licenses/MIT). Alguém tem outra sugestão?

Prazo para resposta: 23 ago. 2020

**Comment by giovana-morais** [comment]
eu gosto dessa. vamo que vamo.

**Comment by biancarosa** [comment]
Gosto tbm!

**Comment by pamellabiotec** [comment]
Qual é a vantagem dessa licença perante as outras? Estou apenas curiosa mesmo.

**Comment by giovana-morais** [comment]
cada licença de código tem suas especificadedes. algumas permitem apenas que o código seja usado sem modificação, outras que o código seja modificado desde que continue público e também aberto a modificações.

tem um mooonte de licenças diferentes, mas a licença MIT, no caso, dá os direitos de usar, copiar, modificar, mergar, publicar, distribuir, criar sub-licenças e/ou vender cópias do software, permitindo também que outras pessoas que queiram possam fazer o mesmo. @cecivieira pode me corrigir se eu falei besteira haha

**Comment by cecivieira** [comment]
Complementando o que Giovana falou, nesse link tem uma visão geral sobre
licenças de software livre e um quadro comparativo.

https://pt.m.wikipedia.org/wiki/Licen%C3%A7a_de_software_livre

**Comment by pamellabiotec** [comment]
Entendi. Obrigada pelo esclarecimento. 🙃
