### ISSUE TITLE
Remover endereço de staging dos resultados do Google

### ISSUE THREAD

**Issue by darlenedms** [pyladies-brazil/br-pyladies-pelican#38]
Acho que seria legal removermos nosso endereço de staging dos resultados do Google, não só para as pessoas não cairem no lugar errado mas para evitar penalização por conteúdo duplicado.

![pyladies-staging](https://cloud.githubusercontent.com/assets/850280/17375652/4988d692-5988-11e6-8e42-96ae22ece62f.png)

**Comment by ellisonleao** [comment]
Podemos criar uma issue para coisas de SEO a fazer.
- Schema.org
- meta e og tags
- twitter cards

etc..
