### ISSUE TITLE
[Blog] Dicas de Python

### ISSUE THREAD

**Issue by danielle8farias-zz** [pyladies-brazil/br-pyladies-pelican#385]
Pensei em colaborar com o blog do site a cada 15 dias com dicas de Python.
Algo que já faço aqui na [Pyladies Sergipe](https://www.instagram.com/pyladiessergipe) as segundas-feiras.

**Comment by giovana-morais** [comment]
vamo que vamo! me comprometo a revisar os textos o mais rápido possível.

**Comment by danielle8farias-zz** [comment]
Obrigada pela ajuda com a revisão. Apanhei um pouco (na verdade, muito) nos passos aqui do github. Marinheira de primeira viagem. >_<

**Comment by giovana-morais** [comment]
hahah normal. cê mandou super bem. (: aguardando pelas próximas contribuições.
