### ISSUE TITLE
Sugestão para novos botões de compartilhamento

### ISSUE THREAD

**Issue by ellisonleao** [pyladies-brazil/br-pyladies-pelican#39]
Meninas, se me permitem, tenho uma sugestão para novos botões de compartilhamento dos posts, usando uma lib que criei , chamada de [Sharer.js](https://github.com/ellisonleao/sharer.js) , que basicamente facilita a dor de cabeça em criar os links de compartilhamento. Podemos adicionar links para outras rede sociais e até redes mobile, como Telegram e Whatsapp.

**Comment by taniaa** [comment]
Obrigada pela sugestão, mas em reunião no dia 9/10/2016, durante a revisão das issues, achamos mais razoável manter como link simples no template do rodapé.
