### ISSUE TITLE
[BUG] Atualizar a versão do Markdown no requirements para a 3.3.1

### ISSUE THREAD

**Issue by biancarosa** [pyladies-brazil/br-pyladies-pelican#397]
**Descreva o bug**

Durante o Hacktoberladies, encontramos um problema de compatibilidade com a versão utilizada do Markdown a versão mais nova do Python (3.9). Achei uma issue referenciando um problema similar. https://github.com/jbarlow83/OCRmyPDF/issues/583

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Utilizando o python 3.6, tente fazer um `pip install -r requirements.txt`
2. Observe o caos

**Comportamento esperado**
A instalação deveria ocorrer normalmente.

**Screenshots**
N/A

**Desktop (complete com as seguintes informações, se aplicável):**
 - SO: Reproduzimos com Windows

**Contexto adicional**
A versão 3.3.1 parece funcionar.

**Comment by giovana-morais** [comment]
acho legal investigar se o problema é só o Markdown mesmo e se compensa a gente fazer uma atualização geral das bibliotecas + versão do python
