### ISSUE TITLE
Encontrar uma maneira fácil de adicionar novos eventos/ladies/locations

### ISSUE THREAD

**Issue by ellisonleao** [pyladies-brazil/br-pyladies-pelican#4]
Atualmente está hardcoded no html de cada página. Podemos tentar ler um json/yaml da vida e popular a página.

**Comment by wiliamsouza** [comment]
Eventos podemos pegar o meetup se usarem e tiver uma API

**Comment by ellisonleao** [comment]
API Meetup http://www.meetup.com/meetup_api/

Como esse site não é apenas o nosso, acredito que seja mais "complicado" usar a api, mas nada impede de um pelican plugin pra pegar os eventos de todas as pyladies e jogar lá.

Client python : https://github.com/meetup/python-api-client

**Comment by ellisonleao** [comment]
Por enquanto vamos adicionando conteúdo modificando os itens na pasta `data` https://github.com/pyladies-curitiba/br-pyladies-pelican/tree/master/data
