### ISSUE TITLE
Inserir informações de e-mail de contato e link do site na página "Locais"

### ISSUE THREAD

**Issue by rsip22** [pyladies-brazil/br-pyladies-pelican#40]
@vanessaromankiv @pgrangeiro

**Comment by taniaa** [comment]
As PyLadies de Curitiba, Campinas, BH, Brasília e Fortaleza não tem e-mail de contato e link do site na página "Locais". Verificar os demais durante o sprint da PythonBrasil[12].

**Comment by jtemporal** [comment]
- [ ] Curitiba - falta o email
- [x] Campinas
- [ ] BH - falta o email
- [x] Brasília
- [ ] Fortaleza - falta o email

duas opções na minha opiniao:
1. sumir com o icone de email quando o grupo não possuir email
2. entrar em contato com as meninas pra colocar o campo de email no data

quanto ao site: não sei se os grupos tem site, mas se tiverem seria legal add o link pra la =)

**Comment by taniaa** [comment]
Bom dia, @jtemporal! Isso cabe em outra issue pode abrir:
"sumir com o icone de email quando o grupo não possuir email"

**Comment by jtemporal** [comment]
boa ideia @taniaa ...

**Comment by jtemporal** [comment]
acho q essa issue foi resolvida... to fechando, caso acharem que não a gnte reabre
