### ISSUE TITLE
[BUG] Página de Dojos não encontrada (404 error)

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#414]
A página Dojos, em vidros, não carrega.

Passos para reproduzir o comportamento:
1. Vá até 'menu’ 
2. Clique em ‘vídeos’ depois ‘Dojos’
3. Veja o erro ‘404 Not Found - nginx/1.16.1’

Testado em:
 - SO:  iOS
 - Browser safari

![32D12175-6EE5-406B-AD98-C3B6782AD6E7](https://user-images.githubusercontent.com/1102067/97840697-58c7df80-1c99-11eb-94d9-3eee3868485d.jpeg)

**Comment by biancarosa** [comment]
Vendo o `videos_dojos.yml` parece que está vazio, e acho que o ideal seria remover. Também removeria o html videos_dojos e o codigo que popula a lista VIDEOS_DOJOS no pelicanconf.py.
Também será necessário remover o link da página videos.
