### ISSUE TITLE
[BUG] Link quebrado na pagina Contributing

### ISSUE THREAD

**Issue by julinvictus** [pyladies-brazil/br-pyladies-pelican#420]
[Site linkado](http://patrick.arminio.info/fix-valueerror-unknown-locale-utf8/) na pagina [contributing](https://github.com/pyladies-brazil/br-pyladies-pelican/blob/master/CONTRIBUTING.md) esta fora do ar.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá até https://github.com/pyladies-brazil/br-pyladies-pelican/blob/master/CONTRIBUTING.md
2. Clique em `Siga esse link: Fix unknown locale`

**Comment by alynnefs** [comment]
Se for esse mesmo escritor, ele mudou de [site](https://patrick.wtf/posts/hello). Mas não tem nada sobre fix value error ainda

**Comment by julinvictus** [comment]
Eu achei esse aqui, alguém me confirma se a info é similar ao quebrado? https://www.railsmine.net/2020/04/how-to-fix-python-error-value-error-unknown-locale-macos.html

**Comment by giovana-morais** [comment]
@julinvictus @alynnefs dei um git blame aqui e vi que esse link ele foi colocado há muuuito tempo atrás, então nem sei qual foi o contexto e se isso ainda acontece durante a instalação do site.
por via das dúvidas, eu recomendo a gente tirar esse link pra tbm não direcionar pra uma solução errada de problema. quando alguém novamente aparecer com o problema, buscamos uma solução em conjunto com a pessoa. talvez tbm possamos reforçar que qualquer problema estaremos de olho nas issues e etc. o que vocês acham?
