### ISSUE TITLE
[Documentação] Adicionar explicação sobre como atualizar o fork

### ISSUE THREAD

**Issue by giovana-morais** [pyladies-brazil/br-pyladies-pelican#423]
À medida que a gente muda algumas coisas importantes, como foi a remoção do arquivo de `ladies.yml` ou a atualização da versão da bibliotecas que usamos, alguns PRs podem vir desatualizados e causar um retrabalho na hora da revisão.

Acho que é importante adicionar na documentação um pequeno trecho pra deixar o fork apontando pro repositório original e lembrando de sempre atualizar o próprio branch antes de fazer a contribuição. :wink:

**Comment by alynnefs** [comment]
A ideia é mudar no README.md ou no CONTRIBUTING.md? Acabei de seguir [esses passos](https://gist.github.com/rdeavila/9618969) e deram certo. Tendo isso definido, posso adicionar a explicação (ou deixo livre pra quem quiser treinar PR)

**Comment by giovana-morais** [comment]
@alynnefs a ideia seria adicionar ao CONTRIBUTING. talvez colocar como um subtópico ou antes de "preparando ambiente local" ou mais pro fim. não sei exatamente onde, estou aberta a sugestões hahaha

**Comment by alynnefs** [comment]
@giovana-morais acho que antes de "preparando ambiente local" é um bom local

obs: dei uma lida no documento e percebi que nunca fiz uma branch específica, sempre usei a principal. Foi mal kkkk

**Comment by alynnefs** [comment]
Estava testando as confirmações do PR #424 e percebi que o link "Adicionar ladies" está quebrado, pois o texto foi removido em algum outro PR. Posso remover nesse PR ou abro outro?

**Comment by giovana-morais** [comment]
pode remover nesse mesmo. é só um link, acho que não vale a pena abrir um PR só pra isso.

**Comment by alynnefs** [comment]
PR atualizado removendo o link 😃

**Comment by giovana-morais** [comment]
obrigada pelo PR! vou fechar essa issue aqui (:
