### ISSUE TITLE
[BUG] todos os builds estão quebrando

### ISSUE THREAD

**Issue by giovana-morais** [pyladies-brazil/br-pyladies-pelican#441]
**Descreva o bug**
auto-explicativo. algo está quebrado no heroku/codeship.
nas últimas explorações que fiz junto com a @jtemporal, o problema aparentou ser no buildpack, mas mesmo quando tentamos acertar as configurações do [repositório](https://github.com/pyladies-brazil/heroku-buildpack-pelican) não obtivemos muito sucesso. hoje fui tentar dar uma olhada novamente no bug, mas não consegui logar no codeship. 

**Contexto adicional**
o erro que estamos tendo dentro do Heroku é 
```
-----> Building on the Heroku-20 stack
-----> Using buildpack: https://github.com/pyladies-brazil/heroku-buildpack-pelican
-----> Pelican app detected
-----> Installing Python (python-3.8.16)
 !     Push rejected, failed to compile Pelican app.
 !     Push failed
```

as mudanças mais recentes feitas são as seguintes:
* atualização do buildpack pro heroku-20 e da versão do python pro 3.8.16 (como especificado na [documentação](https://devcenter.heroku.com/articles/python-support#specifying-a-python-version)): [link](https://github.com/pyladies-brazil/heroku-buildpack-pelican/commit/39514892ac333fd5e394166c8e98d0d26927af1c)
* já tentamos em commits anteriores usarmos o heroku-18 e a versão 3.8.15 do python e recebemos os mesmos erros.

**Próximos passos**
a Jess me disse que o Codeship não é mais uma ferramenta gratuita e que talvez seja a oportunidade que estávamos esperando pra migrar pro GitHub Actions ou Travis CI. acho que podemos usar a issua pra discutir o que vale a pena ou não em mais detalhes.

**Comment by biancarosa** [comment]
cara eu tb nao consigo logar no codeship por nada tb hein


o que vcs acham de gh actions? consigo ajudar fazendo esse setup se quiserem

**Comment by jtemporal** [comment]
O codeship apagou todas as contas free recentemente. Ngm consegue logar, Bia bora setar o Github actions. Eu vou conseguir olhar isso com calma dia 18. Se conseguir fazer algo até lá posta aqui 😉

**Comment by giovana-morais** [comment]
@biancarosa @jtemporal vocês têm um tempo essa semana pra gente olhar isso e migrar pra github actions? não tenho contexto suficiente de todas as ferramentas que são usadas atualmente pra fazer isso sozinha. sei que tem o codeship e o heroku, mas tem mais algum passo?

**Comment by giovana-morais** [comment]
É com muita alegria que estou fechando essa issue. :heart: 

Agora migramos para o GitHub Actions (#445), atualizamos a configuração do Heroku (#443) e temos até um novo problema pra resolver (#447). O grosso está feito e em breve um post-mortem será publicado com os detalhes.
