### ISSUE TITLE
Corrigir link quebrado no rodapé

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/br-pyladies-pelican#45]
O link para a página do google plus ta quebrado, o link certo é esse: https://plus.google.com/114419825361109783805

**Comment by taniaa** [comment]
@pgrangeiro apenas para registro sobre "abrir em nova página", como comentei na reunião de hoje:

"
1.11 Não use janelas pop-up ou abra links em nova janela.  Janelas pop-up são intrusivas e quebram o controle da página. O mesmo ocorre com links que abrem em nova janela. A decisão deve ser do cidadão. Janelas pop-up e links que abrem nova janela também são inacessíveis aos deficientes visuais.
"

Fonte: http://epwg.governoeletronico.gov.br/cartilha-usabilidade
