### ISSUE TITLE
Inserir mais vídeos recentes

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#46]
Conforme reunião das PyLadies do dia 9/10/2016.

**Comment by jtemporal** [comment]
Videos das palestras das pyladies no [Caipyra2016](http://caipyra.python.org.br/):
- [FlapPyLadies: Crie seu primeiro jogo em Python - Jessica Dias](https://www.youtube.com/watch?v=-FDJjk-suAg)
- [Programação além de código - Leticia Portella](https://www.youtube.com/watch?v=yV3XFWfJ0TE)
- [Testes unitários como ferramentas de design de código - Paula Grangeiro](https://www.youtube.com/watch?v=dUVV55qJmyM)

**Comment by jtemporal** [comment]
Tem também as palestras relampago do Caipyra:
- [Barbara](https://youtu.be/FNlSMiVr-vQ?t=4m39s)
- [Jessica Temporal](https://youtu.be/BNmNSHu9bMU?t=15m22s)
- [Júlia Carmona](https://youtu.be/BNmNSHu9bMU?t=23m32s)
- [Juliana Karoline](https://youtu.be/BNmNSHu9bMU?t=50m12s)

**Comment by jtemporal** [comment]
To fuçando isso ;)

**Comment by taniaa** [comment]
Mesa de debate na PythonBrasil 9/PloneConf 2013: "Mulheres na TI: o par XX no mundo Python"
https://youtu.be/cfoE7wmeV78

**Comment by jtemporal** [comment]
Vou fechar essa, caso algm tenha mais algum link, reabre a issue e coloca o link pra gente atualizar =)
