### ISSUE TITLE
Automatizar a lista de próximos eventos e eventos anteriores

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#47]
Conforme reunião das PyLadies do dia 9/10/2016, o ideal seria ajustar via JavaScript a lista dinâmica dos próximos eventos e eventos anteriores, mantendo a alimentação do conteúdo simples em uma arquivo, como é hoje.

**Comment by talitarossari** [comment]
Eu estou fazendo o/

**Comment by rsip22** [comment]
Acredito que foi isso que gerou o Issue #97. Quem puder, verifique.
