### ISSUE TITLE
Melhorar layout da home

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#48]
Conforme reunião das PyLadies do dia 9/10/2016, este ponto deverá ser melhor discutido no sprint da PythonBrasil[12]. Uma ideia era inserir slider de imagens...

**Comment by juhhcarmona** [comment]
Estou trabalhando nisso.

**Comment by talitarossari** [comment]
O que estaria nesse slide de imagens? Fotos dos últimos eventos?

**Comment by jtemporal** [comment]
é uma possibilidade... criar uma pasta do site e colocar algumas fotos das meninas =) temos umas lindas da pybr pra usar =D

**Comment by taniaa** [comment]
Para a home parecer mais dinâmica (ideia inicial), seria bom ter um slider (o de foto, como sugeriu, resolve) e não mostrar eventos passados, apenas do futuro.

**Comment by talitarossari** [comment]
Como assim eventos do futuro?

**Comment by taniaa** [comment]
Seria bom mostrar eventos que ainda ocorrerão. Não mostrar o passado, como é hoje (eventos do dia 21/10/2016 para trás).

**Comment by talitarossari** [comment]
essa melhoria para os eventos seria na pagina de eventos mesmo?
ou na home?

**Comment by taniaa** [comment]
Não, seria na HOME mesmo. A melhoria da página de eventos está em outra issue:
https://github.com/pyladies-brazil/br-pyladies-pelican/issues/104

**Comment by taniaa** [comment]
O que acham de replicar a área "Próximos eventos" na home? http://brasil.pyladies.com/events

Hoje está bem ruim mostrando eventos antigos...

Depois a gente pensa no slider com fotos dos eventos. Acredito que mostrar coisas novas na home já seja algo urgente!

**Comment by jtemporal** [comment]
eu gosto bastante da ideia de colocar os proximos eventos na home no lugar dos blogposts no modelo calendario com é hoje! @taniaa
