### ISSUE TITLE
Mostrar data na lista dos posts de blog, da versão mobile

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#49]
Conforme reunião das PyLadies do dia 9/10/2016. Não faz muito sentido mostrar apenas os títulos dos posts sem mostrar a data em um blog.

**Comment by jtemporal** [comment]
A lista de postagens do blog na versão desktop fica aparecendo a data como abaixo:
![screen shot 2016-10-09 at 22 20 25](https://cloud.githubusercontent.com/assets/6595551/19225236/9b8c779e-8e6e-11e6-9f5f-15f01227b02b.png)

mas na versao mobile não esta aparecendo a data:
![screen shot 2016-10-09 at 22 19 56](https://cloud.githubusercontent.com/assets/6595551/19225235/9a67a6d6-8e6e-11e6-9a5f-c7a2c2d78d7a.png)

**Comment by camilaavilarinho** [comment]
Estou trabalhando nessa

**Comment by camilaavilarinho** [comment]
Resolvido no PR #68
