### ISSUE TITLE
Inserir busca no site

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#50]
Conforme reunião das PyLadies do dia 9/10/2016.

**Comment by pgrangeiro** [comment]
estou trabalhando nesta issue <3

**Comment by pgrangeiro** [comment]
Implementado no PR #88

**Comment by taniaa** [comment]
@pgrangeiro como funciona a busca do site? Procurei por "Brasília" e só achou este post do Blog[1] onde cita "horário de Brasília" quando o esperado seria cair na página de Locais > Brasília ou Ladies, pois tem gente de Brasília... 

[1] http://brasil.pyladies.com/2015/01/22/hangout-pyladies/

**Comment by pgrangeiro** [comment]
A pesquisa só funciona para buscar postagens

**Comment by pgrangeiro** [comment]
Pensando aqui: talvez seja melhor mover essa pesquisa pra dentro da parte blog e procurar um plugin  melhor que faça pesquisa no site inteiro. O que acha @taniaa ?

**Comment by taniaa** [comment]
@pgrangeiro se só funciona para buscas no blog, melhor colocar dentro daquela área do site, senão confunde.
