### ISSUE TITLE
Melhorar layout da página Ladies

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/br-pyladies-pelican#52]
Na versão 47.0 do Firefox pro Ubuntu a página que lista as Ladies está com o layout quebrado. As últimas linhas não mostram os grupos de 3 em 3 ladies como mostra a foto da página.

![screen shot 2016-10-09 at 21 42 11](https://cloud.githubusercontent.com/assets/6595551/19225071/b2bdd5b6-8e69-11e6-9567-30c046eaf52c.png)

**Comment by pgrangeiro** [comment]
Também acontece para Fedora 24 + Google Chrome 53.0 (64 bits)

**Comment by jtemporal** [comment]
se mudar o tamanho da fonte dos nomes das meninas pra 18px já resolve ;)

**Comment by camilaavilarinho** [comment]
Done
