### ISSUE TITLE
Melhorar documentação de inserção de dados no site (arquivo CONTRIBUTING.md)

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#53]
Conforme reunião das PyLadies do dia 9/10/2016, verificamos que os logos da página "Locais" e as imagens da página "PyLadies" não estão seguindo um padrão de tamanho, o que gera distorção nas imagens. Entendemos que é importante inserir a informação sobre o tamanho ideal (100px por 100px) na página de contribuição, depois inserir um comentário no topo de cada página de conteúdo com a âncora para mais informações. Ex de âncora: https://github.com/pyladies-brazil/br-pyladies-pelican/blob/master/CONTRIBUTING.md#adicionar-eventos

**Comment by fullsushidev** [comment]
Estou fazendo essa!

**Comment by fullsushidev** [comment]
Vou fazer apenas a primeira parte! Não entendi a segunda.

**Comment by taniaa** [comment]
Ok, posso fazer a segunda parte quando terminar :)

**Comment by jtemporal** [comment]
Na parte de adição de vídeos tem duas coisas importantes:

1 - o link do vídeo é aquele que se encontra na aba de incorporamento do youtube e não na de compartilhamento.

![screenshot from 2016-10-18 16-52-49](https://cloud.githubusercontent.com/assets/6595551/19491891/59d9ff6a-9553-11e6-8163-0c65ca58d241.png)

2 - colocar como comentário antes do link o título do vídeo para ajudar a não ter conteúdo repetido.

![screenshot from 2016-10-18 16-54-37](https://cloud.githubusercontent.com/assets/6595551/19491947/97e5df18-9553-11e6-9ed3-d1294f37a291.png)

**Comment by fullsushidev** [comment]
Criei a issue #79 para adicionar os itens do comentário da @jtemporal

**Comment by fullsushidev** [comment]
Parte 1 concluída no PR #76! Pode seguir @taniaa ;)

**Comment by fullsushidev** [comment]
@taniaa, criei a issue #86, não sei se foi isso que você quis dizer com a segunda parte desse texto. Estou fazendo isso agora :)

**Comment by jtemporal** [comment]
vou fazer essa segunda parte pra fechar essa issue
