### ISSUE TITLE
Inserir mais contribuidoras na página "Ladies"

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#54]
Conforme reunião das PyLadies do dia 9/10/2016, durante o sprint é importante pedir que todas interessadas insiram seus dados.

**Comment by juhhcarmona** [comment]
Inserindo meus dados. (Finalizado)

**Comment by camilaavilarinho** [comment]
Inserindo meus dados (Finalizado)

**Comment by deboraazevedo** [comment]
Inserindo meus dados (em andamento)

**Comment by jtemporal** [comment]
A deb ja terminou o dela. Vou inserir meus dados (finalizado)

**Comment by fullsushidev** [comment]
A Jéssica já terminou o dela. Inserindo meus dados (FINALIZADO)

**Comment by talitarossari** [comment]
A Ingrid já terminou o dela. Inserindo meus dados (FINALIZADO)

**Comment by douradofefs** [comment]
Adicionei o meu também, pull request feito

**Comment by jtemporal** [comment]
gnt vou fechar essa issue aqui senão ela vai ficar aberta ad ifinitum ;)
