### ISSUE TITLE
Melhorar documentação sobre deploy do site (arquivo CONTRIBUTING.md)

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#55]
Conforme reunião das PyLadies do dia 9/10/2016, esta documentação ajudaria na hora de mais pessoas com permissão subirem as alterações em produção.

**Comment by pgrangeiro** [comment]
Estou com esta issue <3

**Comment by pgrangeiro** [comment]
Resolvido no PR #117
