### ISSUE TITLE
Criar área para materiais no site

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#57]
Conforme reunião das PyLadies do dia 9/10/2016, uma área com materiais de palestras, tutoriais e dojos dados seriam válidos para ajudar outras ladies.

**Comment by taniaa** [comment]
Concluído, correto?
http://brasil.pyladies.com/materiais/

**Comment by camilaavilarinho** [comment]
Observei que não tem nenhuma parte no site com instruções para iniciar um grupo das pyladies. Acho que poderíamos colocar o link para o handbook nessa parte de materiais, o que vocês acham?

**Comment by camilaavilarinho** [comment]
[update]: encontrei uma postagem no blog, mas ainda acho válido colocar nos materiais...

**Comment by jtemporal** [comment]
manda bala @camilaavilarinho acho valido, uma vez que podem ter meninas fuçando o site e darem de cara com o handbook e se interessarem =)

**Comment by camilaavilarinho** [comment]
Feito aqui:  #153

**Comment by darlenedms** [comment]
Ótimo 😄 
Aceitei o PR e está em produção /o/
