### ISSUE TITLE
Traduzir handbook

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies-pelican#59]
Conforme reunião das PyLadies do dia 9/10/2016, durante o sprint da PythonBrasil[12], seria importante revisar e ajustar o handbook. Esta documentação ajuda a todas.

**Comment by julianaklulo** [comment]
Estou trabalhando nisso!

**Comment by julianaklulo** [comment]
Handbook atualizado!
Foi criado um usuário do PyLadies Brasil no Github (https://github.com/pyladies-brasil) para poder utilizar o Gitbook, já que o mesmo não permite criação de livros por organizações, apenas por perfils pessoais.
Segue o link do novo Handbook: https://www.gitbook.com/book/pyladies-brasil/handbook-pyladies/details

**Comment by jtemporal** [comment]
essa issue ta no lugar errado, vou fechar.

**Comment by taniaa** [comment]
Oi, @jtemporal. Pode deixar aqui o link do lugar para ficarem relacionadas?

**Comment by jtemporal** [comment]
@julianaklulo manda o link aqui depois :)
