### ISSUE TITLE
Melhorar layout dos blog posts [versão mobile]

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/br-pyladies-pelican#60]
A versão mobile está com problemas com os títulos dos posts do blog. Se o título conter palavras grandes demais, o layout quebra. Vou colocar prints mais tarde.

**Comment by jtemporal** [comment]
![screenshot_20161010-062154](https://cloud.githubusercontent.com/assets/6595551/19231804/72b44920-8eb2-11e6-9428-0d591f346605.png)

![screenshot_20161010-062158](https://cloud.githubusercontent.com/assets/6595551/19231796/67ee76c8-8eb2-11e6-8e84-f23b6085de9b.png)

**Comment by lusac** [comment]
@jtemporal veja se esse PR resolve! #120

**Comment by pgrangeiro** [comment]
:+1: resolvido
