### ISSUE TITLE
Inserir mais grupos na página "Locais"

### ISSUE THREAD

**Issue by camilaavilarinho** [pyladies-brazil/br-pyladies-pelican#62]
Adicionar mais localizações de grupos de pyladies

**Comment by camilaavilarinho** [comment]
Adicionado o grupo pyladies Teresina no PR #64

**Comment by jtemporal** [comment]
Meninas dos grupos novos, coloquem seus grupos =)

**Comment by jtemporal** [comment]
Inserindo dados do pyladies rp (Finalizado)

**Comment by jtemporal** [comment]
Vamos reodernar a lista de cidades para ficar em ordem alfabetica. issue #81 
(finalizado) #87

**Comment by jtemporal** [comment]
vou fechar essa issue aqui senão ela vai ficar aberta pra sempre... podem ir add mais locais =)
