### ISSUE TITLE
Arrumar links da preview dos posts na versão mobile

### ISSUE THREAD

**Issue by fullsushidev** [pyladies-brazil/br-pyladies-pelican#65]
Os links do site não funcionam na preview dos posts na versão mobile.

**Comment by camilaavilarinho** [comment]
Explica melhor essa issue, pois não entendi. Em que página fica a preview dos posts? pq aqui para mim na página "Blog" os links estão funcionando direitinho.

**Comment by jtemporal** [comment]
os links que aparecem aqui nessa pagina, na versao mobile, nao da pra clicar direto, no Mozilla no ubuntu funciona... mas no mobile nao. ![screenshot from 2016-10-20 20-21-11](https://cloud.githubusercontent.com/assets/6595551/19580069/c454e318-9702-11e6-9461-8d8cd5b6d303.png)

**Comment by lusac** [comment]
@senaingrid @jtemporal vejam se resolve #121 :)

**Comment by pgrangeiro** [comment]
:+1: resolvido
