### ISSUE TITLE
Adicionar um menu chamado Materiais

### ISSUE THREAD

**Issue by annanda** [pyladies-brazil/br-pyladies-pelican#69]
Essa página serviria para colocar links de materiais de Workshop, palestras, etc para que todas as pyladies possam usar em suas cidades. 

Talvez devamos repensar o nome desse menu.

**Comment by geisasantos** [comment]
@annanda é o mesmo que a issue #57 ?
Estava fazendo um texto (md) para sugerir um guia de como poderemos organizar esta área de materiais. Se vamos deixando em aberto para as coordenadoras adicionarem links e informações, sugerir por iniciante/intermediário/avançado (eu penso em outros nominhos mais legais - também como sugestão. 
O que acha? Creio que se deixarmos as sugestões em comentários nas issues complique para acompanhamento e visão geral do andamento.

**Comment by annanda** [comment]
@geisasantos é issue parecida mesmo. Acho ótimo seguir um modelo assim: Iniciante, Intermediário e Avançado.
