### ISSUE TITLE
Corrigir filtro de tempo dos links das palestras relampago

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/br-pyladies-pelican#72]
As palestras relampago do caipyra estão todas num grande vídeo. Por isso precisamos colocar o filtro do tempo. Porém quando fui fazer isso (resolvendo a issue #46) não funcionou.

Precisa descobrir como fazer isso para linkar com o tempo das palestras das meninas.
- Barbara https://youtu.be/FNlSMiVr-vQ?t=4m39s
- Jessica Temporal https://youtu.be/BNmNSHu9bMU?t=15m22s
- Júlia Carmona https://youtu.be/BNmNSHu9bMU?t=23m32s
- Juliana Karoline https://youtu.be/BNmNSHu9bMU?t=50m12s

**Comment by biancarosa** [comment]
doing it!

**Comment by biancarosa** [comment]
@jtemporal É pra retirar os dois links que estão lá das palestras relâmpago do Caipyra e substituir por esses 4 com iniciando no tempo correto, certo?

**Comment by jtemporal** [comment]
issooo!!! @biancarosa por algum motivo nao tava dando certo aqui...

**Comment by biancarosa** [comment]
É pq no embed é `start=xxx` e não `t=xxx`.

Taí. Pull request #90.
Mas fica a sugestão de não usar mais o embed no futuro pq vai ficar ruim de ver quando tiver muitas palestras. Ele também pega o título direto do youtube, o que faz com que os videos tipo esses aí, com start time, fiquem com os titulos do video original.

**Comment by jtemporal** [comment]
Eh mas um problema é que o pelican so aceita o embed. Tentei colocar o de compartilhamento e não foi... Alguma sugestao de alternativa =/
