### ISSUE TITLE
Informar a cidade das líderes de cada grupo

### ISSUE THREAD

**Issue by aninhalacerda** [pyladies-brazil/br-pyladies-pelican#9]
Temos 5 cidades no Brasil e 7 líderes dos grupos.

Seria interessante informar a cidade de cada líder aqui:
http://brazil.pyladies.com/ladies

-- reported by @taniaa 
moved from [issue #18](https://github.com/pyladies-brazil/br-pyladies/issues/18) on the old repo

**Comment by darlenedms** [comment]
Ainda existe esse conceito de "líder"? Acredito que essa issue não faz mais sentido, uma vez que estamos em um modelo mais horizontal.
Convocando algumas ladies pra opinar: @aninhalacerda @annanda @pgrangeiro @kessiacastro @I-am-Gabi @katyanna @rsip22

**Comment by taniaa** [comment]
Acho que a issue deve ser mantida. Não existe a figura de uma líder para uma cidade mais, porém é interessante que as líderes cadastradas no site tenham informação de que Cidade e/ou Estado representam.

**Comment by darlenedms** [comment]
@taniaa Adicionei as cidades no [site](http://brasil.pyladies.com/ladies/), veja se ficou bom, por favor. :]

**Comment by ellisonleao** [comment]
Eu achei legal, só acho que poderia dar uma mudada no hover do link, tá meio estranho agora

![screen shot 2016-08-04 at 8 06 29 pm](https://cloud.githubusercontent.com/assets/178641/17421282/12b9e5b4-5a7f-11e6-8eef-70332836be6a.png)

**Comment by darlenedms** [comment]
@ellisonleao Como nessa história não mexi em nada desses links, só adicionei a informação de cidade embaixo do nome, sugiro criar outra issue pra tratar desse hover.

**Comment by ellisonleao** [comment]
@darlenedms entendi, mas por ser uma easy fix resolvi só deixar aqui e não abri a issue..

**Comment by taniaa** [comment]
Achei lindo!
