### ISSUE TITLE
Corrigir Eventos

### ISSUE THREAD

**Issue by rsip22** [pyladies-brazil/br-pyladies-pelican#97]
Todos eventos acabaram ficando como "Eventos anteriores". Precisa corrigir isso para que os eventos a partir da data "hoje" fiquem como "Próximos eventos".

**Comment by jtemporal** [comment]
@talitarossari alguma ideia do q pode ter rolado?

**Comment by talitarossari** [comment]
Darei uma olhada aqui!

**Comment by talitarossari** [comment]
Aqui deu tudo certo, @rsip22, pode mandar o screenshot disso?
![pyladies_screenshot](https://cloud.githubusercontent.com/assets/9342260/19518336/68744f02-95e5-11e6-8012-a827b2a86ba1.png)

**Comment by rsip22** [comment]
Aqui está assim, tanto no desktop (Mozilla) quanto no iPad (screenshot)

![image](https://cloud.githubusercontent.com/assets/16676222/19521265/bffd11da-95f1-11e6-8455-c421c81f56aa.jpeg)

**Comment by talitarossari** [comment]
O formato de data do Mozilla é inferior ao Chrome, dai tava dando bug, porem resolvi o/ (espero)

**Comment by rsip22** [comment]
No Mozilla corrigiu. O problema persiste no Safari (desktop e iOS).

**Comment by talitarossari** [comment]
No safari eu não tenho como testar... tem alguma menina que consiga resolver isso?
#help

**Comment by darlenedms** [comment]
@rsip22 pode re-testar agora, por favor?

**Comment by rsip22** [comment]
Funcionou \o/

**Comment by talitarossari** [comment]
NUNCA MAIS RECLAMO DE PESSOAS COM MACBOOK <3
@darlenedms, ce é incrivel <3
