### ISSUE TITLE
Criar busca para todo conteúdo do site (na versão responsiva, ficar abaixo do logo)

### ISSUE THREAD

**Issue by rsip22** [pyladies-brazil/br-pyladies-pelican#98]
Conforme conversado no sprint, para a caixa de busca ser maior, responsiva, etc.

**Comment by amimenezes** [comment]
O que vocês pensam sobre a caixa de busca ficar na página principal?
E, o que vocês pensam sobre o "navbar" ser fixado no topo das páginas?

**Comment by jtemporal** [comment]
como assim ficar na pagina principal @mml88 ?

**Comment by amimenezes** [comment]
Na "index.html" ;)

**Comment by rsip22** [comment]
A caixa de busca na barra de navegação, não ter de clicar no menu e abrir outra página para pesquisar. Alguém sabe se isso foi cogitado? @pgrangeiro ?

**Comment by taniaa** [comment]
Não sei o que foi discutido no sprint, mas o ideal é ter no topo da página por toda navegação do site, não clicar para aparecer a busca. E na versão responsiva ficar abaixo do logo, por exemplo.

**Comment by pgrangeiro** [comment]
@rsip22 @taniaa a busca tem q de fato sair daquele menu pesquisar pois dá a impressão de que é possível pesquisar por todo o site. O plugin de busca que foi colocado **não realiza busca em todo o site**, só nas postagens. Teria que ver se existe algum plugin que tenha a funcionalidade de varrer todos os estáticos (acho dificil).

**Comment by taniaa** [comment]
@pgrangeiro então melhor ficar como discutimos na outra issue: mover a busca atual para dentro da página de blog. Vou mudar o nome desta issue para criar busca para site (geral).
